version: '3'
services:
  spiderfoot-rest:
    build: ./
    container_name: spiderfoot-rest
    restart: on-failure
    volumes:
      - ./application:/application
    ports:
      - "5000:5000"
    command: python main.py